### ISSUE TITLE
关于本地开发环境搭配问题

### ISSUE THREAD

**Issue by cipchk** [bidianqing/SSO.Core.Sample#1]
文中指出【发到文件系统默认的路径应该是bin\Release\PublishOutput】，我想问一下，若一个解决方案当中有三个网站 H5、Cached、Trade，基于此我有几个问题：

+ 实际在开发中，Cached 是被H5&Trade调用，那如果让这三个网站同时能运行呢？
+  `bin\Release\PublishOutput` 不意味者每一次修改都需要发布动作吗？
+ 透过域名访问又当如何DEBUG呢？

**Comment by bidianqing** [comment]
@cipchk 希望这篇文章能帮助到你 谢谢！ http://www.cnblogs.com/bidianqing/p/7461281.html

**Comment by cipchk** [comment]
谢谢指点，不过文中可以增加一点描述。

IIS中其实是可以直接指向项目的根目录的，这样可以确保编译后直接刷新即生效。

再次感谢。

**Comment by bidianqing** [comment]
已经在文中增加了一点描述，明确指明IIS是可以指向项目的根目录的，非常感谢你的反馈
